language: bash

services: docker

env:
  global:
    - secure: "RQELxWUDOmrs31NEMuSwxYsRoYtFRJJnhNc+JHEpS2yf8LK47zn8sDV/lwsf1UGHzWF3rkdbfEhi46N627CeziyiXo7y4EzIjK24x0tJZXLFYe685wHpzpbDgJ+5Zdx0J4SJfImX6VBJ+QpRcU4o2GC3uWAd+qnRjbkjVxlcmGT8mJOShBAo8mgrPuV2tbsyr3tE+O5CsfZCiBR2kVG6oM3WKR1sJaX/3lGv66bXg4yJIDHekqCnozihYl48x9Y3qAYXyOUWTrEyK9wPsSer52bYYOqQkuVPum4/pmF2jGHrIAEFEifVzxG2C7T12ev7HaXrrkHYhZmizL608QZpiWvct1T04wKQUKxR+ji3lrE4IvRVZefz/FFe+Xcynh/4EO05oWO3vF9VJssXaPVW2cgPfwVAK50gF3fyp/wuPXDEZD7OaIJsGeovn8D8tImvQ8UqMWwT4c4YtZ8G5REjoiRdw0MaKKctf0Yk9NYmUf0jhX0LjCCsyx7+oT9lH9EX3eGrqVT27eq59Yaxn6hksAQPfafFZFaUUmly9bnMXReaa0KsLhKtopMhQRjtVrIO8zFVBPeIVf02iQNaOySpdCerj3GsXVLvR9izWF50grrkuDeIgb2rFgTdPI2rTkEVaFwyikWhCM8vlizKfZTWJQQQhBOnS0z4rlITZdXjoF4="
    - secure: "Zmg6VKLEmSKWHTUl3hg4fvrGD+5/BRckpxC6hmNo4J5fCfVHXiWOK9+HJJOVXiux29l8/kF0Gu43Wcv4YPFwxWp/qrl5XWfKRTajUW//yNA0ROaq081srHYzFXcQHnTx3YIfT0FKq4lhbk21PKzXIaGG6z9RwvB7TJY4H+TQeOsCteHMYl/0LfGmLOkMdEWs5DDmZk7v0WfUqT5vhEq0kDqYtUbCuuWeckv+UWtuzJRGTI+4HLCmN4A+jQXqL9t3gGr9/9Fn061kVyuvt1GxzBuGfiYqkSmTWMdD+UEkYBFG4SVEOn1NGM47Ki5DnTZZ7GgFYzuftGPJ72DDP1Upxkk82ZQXY2m5Jh7dDx/70jcJfx4Tc8HVI9LqLFesp4R9BOir7EQIHDBKWvj+uvL23PzBqKN8AsCC8dfIwf9Gg0zw//6iQPXZhiJI2ArB8VuCa0AdTq74h16w6Vjs5l1bRRyEn22nN1i8HVRl2lspx9DwkC9z9q4NFwG6c+GuWwEcx50pGuh+kF2xng6nAWEHSscp6LdURj9RkxNis4/HUqM2qr9lwJEILdNqrxMp0Qcjp8UynNY/tVdB7D/0VbPULH8p6uweGXStor+YBNbjLGwxDhhlQf1eUIbcLGpdQLdLWpDI8sLMqbr4XWBKElPyzCRt2twqOVLUi8CTvF3V6JM="
  matrix:
    - VERSION=latest

before_script:
  - cd src/
  - IMAGE_NAME="chesszebra/$(echo "$TRAVIS_REPO_SLUG" | cut -c 25-):${VERSION}"

script:
  - docker build -t "$IMAGE_NAME" .

after_success:
  - docker login --username $DOCKER_USER --password $DOCKER_PASS
  - docker push $IMAGE_NAME

after_script:
  - docker images

notifications:
  email: false
